#!/usr/bin/env python3
"""Emit the Dart leg barrels from whatever buf just generated.

Dart export directives have no aliasing — only show/hide — so a single barrel
cannot surface two classes that share a name. `GatewayError` is declared on both
the connector leg (connector/v1) and the app leg (webrtc/v1), deliberately and
with different semantics, so one barrel over the whole package is not
expressible. Two leg barrels are: the colliding names never co-occur on one leg.

Generating them rather than hand-writing them is the other half of the fix. The
previous hand-written barrel drifted 25 files behind the generated tree,
including the enum file carrying GatewayErrorCode, because nothing tied it to
what buf emits.

Run after `buf generate --template buf.gen.dart.yaml`; the Jenkins Generate
stage does exactly that.
"""

import pathlib
import sys

LIB = pathlib.Path(__file__).parent / "gen" / "dart" / "lib"
PKG = "kusinta/iot"

# Leg membership by proto package directory. Anything not named here is
# leg-neutral and goes into both barrels.
APP_ONLY = {"webrtc", "signaling"}
CONNECTOR_ONLY = {"connector"}

# .pbjson.dart is descriptor data the .pb.dart already imports, and
# .pbserver.dart is the legacy Dart server stub. Neither belongs in a public
# surface.
SUFFIXES = (".pb.dart", ".pbenum.dart", ".connect.client.dart")

HEADER = """// GENERATED by gen-dart-barrels.py — do not edit by hand.
//
// {what}
//
// Dart cannot alias an export, so the package ships one barrel per leg rather
// than one overall: `GatewayError` is declared on both the connector leg and
// the app leg, with different semantics, and no single library can surface
// both. Import the barrel for your leg, or import the generated files directly.
"""


def domain(rel: pathlib.Path) -> str:
    """kusinta/iot/<domain>/v1/x.pb.dart -> <domain>"""
    return rel.parts[2]


def collect() -> list[pathlib.Path]:
    root = LIB / PKG
    if not root.is_dir():
        sys.exit(f"{root} not found — run buf generate first")
    files = [
        p.relative_to(LIB)
        for p in sorted(root.rglob("*.dart"))
        if p.name.endswith(SUFFIXES)
    ]
    if not files:
        sys.exit(f"no generated Dart files under {root}")
    return files


def write(name: str, what: str, keep) -> int:
    lines = [HEADER.format(what=what)]
    for rel in collect():
        d = domain(rel)
        if keep(d):
            lines.append(f"export '{rel.as_posix()}';")
    out = LIB / name
    out.write_text("\n".join(lines) + "\n")
    return len(lines) - 1


def main() -> None:
    app = write(
        "app.dart",
        "The app leg: the WebRTC data channel and signaling, plus the "
        "leg-neutral domain types.",
        lambda d: d not in CONNECTOR_ONLY,
    )
    conn = write(
        "connector.dart",
        "The connector leg: the connector session protocol, plus the "
        "leg-neutral domain types.",
        lambda d: d not in APP_ONLY,
    )
    print(f"app.dart: {app} exports\nconnector.dart: {conn} exports")


if __name__ == "__main__":
    main()
