syntax = "proto3";

package kusinta.iot.v1.space;

import "common/types.proto";
import "identity/identity.proto";

option optimize_for = SPEED;

message Space {
  kusinta.iot.v1.identity.SpaceId   space_id         = 1;
  kusinta.iot.v1.common.SpaceType   space_type       = 2;
  string                            name             = 3;
  string                            description      = 4;
  int32                             floor            = 5; // meaningful for FLOOR type
  kusinta.iot.v1.identity.SpaceId   parent_space_id  = 6; // null for top-level Building
  repeated kusinta.iot.v1.identity.SpaceId  sub_space_ids    = 7;
  repeated kusinta.iot.v1.identity.DeviceId device_ids       = 8;
  kusinta.iot.v1.identity.UserId    resident_user_id = 9; // only for APARTMENT
  kusinta.iot.v1.identity.TenantId  tenant_id        = 10;
  kusinta.iot.v1.identity.GatewayId gateway_id       = 11;
}
