name: kusinta_iot_schema
description: Generated protobuf message types for the Kusinta IoT platform.
# Set via ./set-version.sh <version>
version: 0.1.0-beta.19
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  protobuf: ^4.1.0
  connectrpc: ^1.0.0
